import { appBuildInfo } from "../buildInfo";
import { getTelegramRuntimeDiagnostics } from "../telegram/webapp";
import { getStartupTrace, traceStartup } from "./startupTrace";
import { getLifecycleTrace, lifecycleTrace } from "./lifecycleTrace";
import { saveCrashDump } from "./crashDump";

export type DiagnosticEvent = { timestamp:string; elapsedMs:number; event:string; details?:Record<string,unknown> };
export type NetworkEvent = DiagnosticEvent & { requestId:string; method?:string; url?:string; status?:number; durationMs?:number; aborted?:boolean; timeout?:boolean };

declare global { interface Window { BLOOM_DEBUG?: boolean; __BLOOM_DEBUG_ENABLED__?: boolean; __BLOOM_STARTUP_SESSION_ID__?: string; __BLOOM_CATALOG_TRACE__?: DiagnosticEvent[]; __BLOOM_NETWORK_TRACE__?: NetworkEvent[]; __BLOOM_ERROR_TRACE__?: DiagnosticEvent[]; __BLOOM_ABORT_TRACE__?: DiagnosticEvent[]; __BLOOM_ORIGINAL_FETCH__?: typeof fetch; __BLOOM_ORIGINAL_ABORT_CONTROLLER__?: typeof AbortController; __BLOOM_DIAGNOSTICS_INSTALLED__?: boolean; __BLOOM_OPEN_DIAGNOSTICS__?: (reason?: string) => void; } }

const start = Date.now();
const MAX = 250;
const SENSITIVE = /^(authorization|initdata|init_data|telegram_payload|access_token|token|signature|credential|cookie|secret|password)$/i;

export function getStartupSessionId(): string {
  if (typeof window === "undefined") return "server";
  if (!window.__BLOOM_STARTUP_SESSION_ID__) window.__BLOOM_STARTUP_SESSION_ID__ = crypto.randomUUID?.() ?? `startup-${Date.now()}-${Math.random().toString(36).slice(2)}`;
  return window.__BLOOM_STARTUP_SESSION_ID__;
}

export function isBloomDebugEnabled(): boolean {
  if (typeof window === "undefined") return false;
  try { return window.BLOOM_DEBUG === true || window.__BLOOM_DEBUG_ENABLED__ === true || localStorage.getItem("BLOOM_DEBUG") === "1" || sessionStorage.getItem("BLOOM_DEBUG") === "1"; } catch { return window.BLOOM_DEBUG === true || window.__BLOOM_DEBUG_ENABLED__ === true; }
}
export function enableBloomDebug(): void { if (typeof window === "undefined") return; window.__BLOOM_DEBUG_ENABLED__ = true; try { localStorage.setItem("BLOOM_DEBUG", "1"); } catch {} }

function cleanText(s:string): string { return s.replace(/(Authorization\s*[:=]\s*)[^\s,}]+/gi,"$1[redacted]").replace(/([?&#]?(?:initData|init_data|telegram_payload|access_token|token|signature|hash)=)([^&\s]+)/gi,"$1[redacted]").slice(0,900); }
export function sanitizeDiagnostics(value: unknown, depth=0): unknown { if(depth>4) return "[depth-limit]"; if(value instanceof Error) return {name:value.name,message:cleanText(value.message),stack:cleanText(value.stack??"").slice(0,1200)}; if(typeof value==="string") return cleanText(value); if(typeof value==="number"||typeof value==="boolean"||value===null) return value; if(Array.isArray(value)) return value.slice(0,40).map(v=>sanitizeDiagnostics(v,depth+1)); if(value && typeof value==="object") return Object.fromEntries(Object.entries(value as Record<string,unknown>).map(([k,v])=>[k,SENSITIVE.test(k)?"[redacted]":sanitizeDiagnostics(v,depth+1)])); return undefined; }
function push<T extends DiagnosticEvent>(key:"__BLOOM_CATALOG_TRACE__"|"__BLOOM_NETWORK_TRACE__"|"__BLOOM_ERROR_TRACE__"|"__BLOOM_ABORT_TRACE__", event:T): T { if(typeof window!=="undefined"){ const a=(window[key]??[]) as T[]; a.push(event); if(a.length>MAX) a.splice(0,a.length-MAX); (window as any)[key]=a; } return event; }
function ev(event:string, details?:unknown): DiagnosticEvent { return {timestamp:new Date().toISOString(),elapsedMs:Math.max(0,Date.now()-start),event,details:sanitizeDiagnostics(details) as Record<string,unknown>|undefined}; }
export function catalogTrace(event:string, details?:unknown): DiagnosticEvent { traceStartup(event, details); return push("__BLOOM_CATALOG_TRACE__", ev(event, details)); }
export function errorTrace(event:string, details?:unknown): DiagnosticEvent { const entry = push("__BLOOM_ERROR_TRACE__", ev(event, details)); saveCrashDump(event, { criticalEvent: event }); return entry; }

function urlOf(input: RequestInfo | URL): string { try { return input instanceof Request ? input.url : String(input); } catch { return "[unknown]"; } }
function methodOf(input: RequestInfo | URL, init?: RequestInit): string { return (init?.method || (input instanceof Request ? input.method : "GET")).toUpperCase(); }
function installFetch(): void { if(window.__BLOOM_ORIGINAL_FETCH__) return; const original=window.fetch.bind(window); window.__BLOOM_ORIGINAL_FETCH__=window.fetch; window.fetch = async (input:RequestInfo|URL, init?:RequestInit) => { const requestId=`fe-${Date.now()}-${Math.random().toString(36).slice(2,8)}`; const started=performance.now(); const url=cleanText(urlOf(input)); const method=methodOf(input,init); push("__BLOOM_NETWORK_TRACE__", {...ev("request created",{requestId,method,url}),requestId,method,url}); let nextInit=init?{...init}:{}; push("__BLOOM_NETWORK_TRACE__", {...ev("headers prepared",{requestId}),requestId,method,url}); const headers=new Headers(nextInit.headers || (input instanceof Request ? input.headers : undefined)); headers.set("X-Startup-Session", getStartupSessionId()); nextInit.headers=headers; push("__BLOOM_NETWORK_TRACE__", {...ev("signal attached",{requestId,hasSignal:Boolean(nextInit.signal)}),requestId,method,url}); push("__BLOOM_NETWORK_TRACE__", {...ev("timeout attached",{requestId,detected:false}),requestId,method,url,timeout:false}); push("__BLOOM_NETWORK_TRACE__", {...ev("request started",{requestId}),requestId,method,url}); try { const r=await original(input,nextInit); const durationMs=Math.round(performance.now()-started); push("__BLOOM_NETWORK_TRACE__", {...ev("response received",{requestId,status:r.status,durationMs}),requestId,method,url,status:r.status,durationMs,aborted:false}); return r; } catch(e) { const durationMs=Math.round(performance.now()-started); const aborted=e instanceof DOMException && e.name==="AbortError"; push("__BLOOM_NETWORK_TRACE__", {...ev(aborted?"request aborted":"request failed",{requestId,error:e,durationMs}),requestId,method,url,durationMs,aborted}); if (aborted) saveCrashDump("AbortError", { requestId, method, catalogAborted: true }); throw e; } }; }
function installAbort(): void { if(window.__BLOOM_ORIGINAL_ABORT_CONTROLLER__) return; const Original=window.AbortController; window.__BLOOM_ORIGINAL_ABORT_CONTROLLER__=Original; window.AbortController = class BloomAbortController extends Original { __id=`abort-${Date.now()}-${Math.random().toString(36).slice(2,8)}`; __stack=new Error("AbortController created").stack; constructor(){ super(); push("__BLOOM_ABORT_TRACE__", ev("controller created",{controllerId:this.__id,creationStack:this.__stack})); this.signal.addEventListener("abort",()=>{ push("__BLOOM_ABORT_TRACE__", ev("signal aborted",{controllerId:this.__id,reason:String((this.signal as any).reason??"")})); saveCrashDump("AbortError", { controllerId: this.__id }); },{once:true}); } abort(reason?:any){ push("__BLOOM_ABORT_TRACE__", ev("abort called",{controllerId:this.__id,reason:String(reason??""),abortStack:new Error("AbortController.abort called").stack,creationStack:this.__stack})); saveCrashDump("AbortError", { controllerId: this.__id }); return super.abort(reason); } } as typeof AbortController; }
export function installProductionDiagnostics(): void { if(typeof window==="undefined"||window.__BLOOM_DIAGNOSTICS_INSTALLED__) return; window.__BLOOM_DIAGNOSTICS_INSTALLED__=true; getStartupSessionId(); traceStartup("startup_session_created",{startupSessionId:getStartupSessionId()}); installAbort(); installFetch(); window.addEventListener("error", e=>errorTrace("window.onerror",{message:e.message,filename:e.filename,lineno:e.lineno,colno:e.colno,error:e.error})); window.addEventListener("unhandledrejection", e=>errorTrace("unhandledrejection",{reason:e.reason})); lifecycleTrace("production_diagnostics_installed",{startupSessionId:getStartupSessionId(),debugEnabled:isBloomDebugEnabled()}); }
export function createProductionDiagnosticSnapshot(reason="manual"): Record<string,unknown> { const tg=getTelegramRuntimeDiagnostics(); return { reason, startupSessionId:getStartupSessionId(), buildHash:appBuildInfo.buildHash, buildDate:appBuildInfo.buildTimestamp, appVersion:appBuildInfo.buildVersion, startupTrace:getStartupTrace(), catalogTrace:typeof window==="undefined"?[]:window.__BLOOM_CATALOG_TRACE__??[], networkTrace:typeof window==="undefined"?[]:window.__BLOOM_NETWORK_TRACE__??[], abortTrace:typeof window==="undefined"?[]:window.__BLOOM_ABORT_TRACE__??[], errors:typeof window==="undefined"?[]:window.__BLOOM_ERROR_TRACE__??[], lifecycleTrace:getLifecycleTrace(), flags:{ debugEnabled:isBloomDebugEnabled(), startupFinished:getStartupTrace().some(e=>e.step==="bootstrap_done"), startupFailed:getStartupTrace().some(e=>e.step.includes("fail")), catalogRequested:getStartupTrace().some(e=>e.step.includes("catalog")||e.step.includes("Partners")), hasToken:false }, telegram:tg, browser:{ userAgent:navigator.userAgent, language:navigator.language, viewport:{width:innerWidth,height:innerHeight,devicePixelRatio}, currentPage:document.title, currentRoute:location.pathname+location.search+location.hash } }; }
