-- Bloom Club client/referral/trial contract migration.
-- Apply on WEB backend database before deploying Mini App referral/trial UI.

ALTER TABLE clients
  ADD COLUMN IF NOT EXISTS trial_used BOOLEAN NOT NULL DEFAULT FALSE,
  ADD COLUMN IF NOT EXISTS trial_available BOOLEAN NOT NULL DEFAULT TRUE,
  ADD COLUMN IF NOT EXISTS referral_code TEXT,
  ADD COLUMN IF NOT EXISTS referral_link TEXT;

CREATE UNIQUE INDEX IF NOT EXISTS ux_clients_telegram_user_id
  ON clients (telegram_user_id)
  WHERE telegram_user_id IS NOT NULL;

CREATE UNIQUE INDEX IF NOT EXISTS ux_clients_referral_code
  ON clients (referral_code)
  WHERE referral_code IS NOT NULL;

CREATE TABLE IF NOT EXISTS client_referrals (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  referrer_client_id BIGINT NOT NULL REFERENCES clients(id) ON DELETE CASCADE,
  referred_client_id BIGINT NOT NULL REFERENCES clients(id) ON DELETE CASCADE,
  referral_code TEXT NOT NULL,
  status TEXT NOT NULL DEFAULT 'pending',
  reward_entries_count INTEGER NOT NULL DEFAULT 5,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  activated_at TIMESTAMPTZ,
  CONSTRAINT ck_client_referrals_not_self CHECK (referrer_client_id <> referred_client_id),
  CONSTRAINT ux_client_referrals_referred UNIQUE (referred_client_id)
);

CREATE INDEX IF NOT EXISTS ix_client_referrals_referrer_client_id ON client_referrals (referrer_client_id);
CREATE INDEX IF NOT EXISTS ix_client_referrals_referral_code ON client_referrals (referral_code);
CREATE INDEX IF NOT EXISTS ix_client_referrals_status ON client_referrals (status);

CREATE TABLE IF NOT EXISTS giveaway_entries (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  client_id BIGINT NOT NULL REFERENCES clients(id) ON DELETE CASCADE,
  giveaway_id BIGINT,
  source TEXT NOT NULL,
  entries_count INTEGER NOT NULL CHECK (entries_count > 0),
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  related_referral_id BIGINT REFERENCES client_referrals(id) ON DELETE SET NULL
);

CREATE UNIQUE INDEX IF NOT EXISTS ux_giveaway_entries_referral_reward
  ON giveaway_entries (related_referral_id)
  WHERE source = 'referral' AND related_referral_id IS NOT NULL;

CREATE INDEX IF NOT EXISTS ix_giveaway_entries_client_id ON giveaway_entries (client_id);
CREATE INDEX IF NOT EXISTS ix_giveaway_entries_giveaway_id ON giveaway_entries (giveaway_id);
CREATE INDEX IF NOT EXISTS ix_giveaway_entries_source ON giveaway_entries (source);

-- WEB backend login/register contract:
-- 1. Resolve referral_code/start_param to clients.referral_code.
-- 2. Insert client_referrals with clients.id values, not Telegram user ids.
-- 3. Keep referral pending until trial activation succeeds.
CREATE OR REPLACE FUNCTION register_client_referral_if_needed(
  p_referred_client_id BIGINT,
  p_referral_code TEXT
) RETURNS BIGINT AS $$
DECLARE
  v_referrer_client_id BIGINT;
  v_referral_id BIGINT;
  v_referral_code TEXT := NULLIF(BTRIM(p_referral_code), '');
BEGIN
  IF v_referral_code IS NULL THEN
    RETURN NULL;
  END IF;

  SELECT id
    INTO v_referrer_client_id
    FROM clients
   WHERE referral_code = v_referral_code
   LIMIT 1;

  IF v_referrer_client_id IS NULL OR v_referrer_client_id = p_referred_client_id THEN
    RETURN NULL;
  END IF;

  INSERT INTO client_referrals (referrer_client_id, referred_client_id, referral_code, status)
  VALUES (v_referrer_client_id, p_referred_client_id, v_referral_code, 'pending')
  ON CONFLICT (referred_client_id) DO NOTHING
  RETURNING id INTO v_referral_id;

  IF v_referral_id IS NULL THEN
    SELECT id
      INTO v_referral_id
      FROM client_referrals
     WHERE referred_client_id = p_referred_client_id;
  END IF;

  RETURN v_referral_id;
END;
$$ LANGUAGE plpgsql;

-- WEB backend trial activation contract:
-- Mark exactly the pending referral for this client successful and award 5 entries
-- to referrer_client_id. giveaway_entries.client_id is always clients.id.
CREATE OR REPLACE FUNCTION activate_pending_referral_reward(
  p_referred_client_id BIGINT
) RETURNS BIGINT AS $$
DECLARE
  v_referral client_referrals%ROWTYPE;
  v_entry_id BIGINT;
BEGIN
  SELECT *
    INTO v_referral
    FROM client_referrals
   WHERE referred_client_id = p_referred_client_id
     AND status = 'pending'
   FOR UPDATE;

  IF NOT FOUND THEN
    RETURN NULL;
  END IF;

  UPDATE client_referrals
     SET status = 'successful',
         activated_at = COALESCE(activated_at, CURRENT_TIMESTAMP)
   WHERE id = v_referral.id;

  INSERT INTO giveaway_entries (client_id, giveaway_id, source, entries_count, related_referral_id)
  VALUES (v_referral.referrer_client_id, NULL, 'referral', v_referral.reward_entries_count, v_referral.id)
  ON CONFLICT (related_referral_id) WHERE source = 'referral' AND related_referral_id IS NOT NULL DO NOTHING
  RETURNING id INTO v_entry_id;

  RETURN v_entry_id;
END;
$$ LANGUAGE plpgsql;

-- WEB backend /api/v1/clients/me/referral response should derive counters from clients.id:
-- pending_referrals_count: count client_referrals where referrer_client_id = current client id and status = 'pending'
-- activated_referrals_count/referrals_count/invited_count: count where status = 'successful'
-- earned_entries_count/earned_giveaway_entries_count: sum giveaway_entries.entries_count where client_id = current client id and source = 'referral'
