"""Database helpers for the Telegram catalog."""
from __future__ import annotations

import importlib.util
import sqlite3
from pathlib import Path
from typing import Any
from urllib.parse import unquote, urlparse

from .config import get_settings

SQLITE_SCHEMA_SQL = """
PRAGMA foreign_keys = ON;

CREATE TABLE IF NOT EXISTS telegram_partners (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    external_content_id INTEGER UNIQUE,
    title TEXT NOT NULL,
    display_name TEXT,
    description TEXT,
    city TEXT,
    category TEXT,
    address TEXT,
    phone TEXT,
    is_active INTEGER NOT NULL DEFAULT 1,
    sort_order INTEGER NOT NULL DEFAULT 0,
    created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS ix_telegram_partners_is_active
    ON telegram_partners (is_active);
CREATE INDEX IF NOT EXISTS ix_telegram_partners_sort_order
    ON telegram_partners (sort_order);

CREATE TABLE IF NOT EXISTS telegram_partner_photos (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    partner_id INTEGER NOT NULL REFERENCES telegram_partners(id) ON DELETE CASCADE,
    external_content_id INTEGER UNIQUE,
    image_url TEXT,
    file_path TEXT,
    sort_order INTEGER NOT NULL DEFAULT 0,
    is_cover INTEGER NOT NULL DEFAULT 0,
    created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CHECK (image_url IS NOT NULL OR file_path IS NOT NULL)
);

CREATE INDEX IF NOT EXISTS ix_telegram_partner_photos_partner_id
    ON telegram_partner_photos (partner_id);
CREATE INDEX IF NOT EXISTS ix_telegram_partner_photos_sort_order
    ON telegram_partner_photos (sort_order);

CREATE TABLE IF NOT EXISTS telegram_partner_offers (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    partner_id INTEGER NOT NULL REFERENCES telegram_partners(id) ON DELETE CASCADE,
    external_content_id INTEGER UNIQUE,
    title TEXT NOT NULL,
    description TEXT,
    conditions TEXT,
    base_price REAL,
    member_price REAL,
    discount_percent REAL,
    is_active INTEGER NOT NULL DEFAULT 1,
    sort_order INTEGER NOT NULL DEFAULT 0,
    created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS ix_telegram_partner_offers_partner_id
    ON telegram_partner_offers (partner_id);
CREATE INDEX IF NOT EXISTS ix_telegram_partner_offers_is_active
    ON telegram_partner_offers (is_active);
CREATE INDEX IF NOT EXISTS ix_telegram_partner_offers_sort_order
    ON telegram_partner_offers (sort_order);

CREATE TABLE IF NOT EXISTS telegram_privilege_codes (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    telegram_user_id TEXT,
    linked_client_id TEXT,
    web_client_id TEXT,
    linked_account_id TEXT,
    partner_id INTEGER NOT NULL REFERENCES telegram_partners(id) ON DELETE CASCADE,
    offer_id INTEGER REFERENCES telegram_partner_offers(id) ON DELETE SET NULL,
    code TEXT NOT NULL UNIQUE,
    status TEXT NOT NULL DEFAULT 'created',
    expires_at TEXT,
    used_at TEXT,
    created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    source_platform TEXT NOT NULL DEFAULT 'telegram',
    web_subscription_checked_at TEXT,
    access_snapshot TEXT,
    metadata TEXT
);

CREATE INDEX IF NOT EXISTS ix_telegram_privilege_codes_partner_id
    ON telegram_privilege_codes (partner_id);
CREATE INDEX IF NOT EXISTS ix_telegram_privilege_codes_offer_id
    ON telegram_privilege_codes (offer_id);
CREATE INDEX IF NOT EXISTS ix_telegram_privilege_codes_status
    ON telegram_privilege_codes (status);
CREATE INDEX IF NOT EXISTS ix_telegram_privilege_codes_expires_at
    ON telegram_privilege_codes (expires_at);
CREATE INDEX IF NOT EXISTS ix_telegram_privilege_codes_telegram_user_id
    ON telegram_privilege_codes (telegram_user_id);
CREATE INDEX IF NOT EXISTS ix_telegram_privilege_codes_linked_client_id
    ON telegram_privilege_codes (linked_client_id);
"""

POSTGRES_SCHEMA_SQL = """
CREATE TABLE IF NOT EXISTS telegram_partners (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    external_content_id INTEGER UNIQUE,
    title TEXT NOT NULL,
    display_name TEXT,
    description TEXT,
    city TEXT,
    category TEXT,
    address TEXT,
    phone TEXT,
    is_active INTEGER NOT NULL DEFAULT 1,
    sort_order INTEGER NOT NULL DEFAULT 0,
    created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP::TEXT,
    updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP::TEXT
);

CREATE INDEX IF NOT EXISTS ix_telegram_partners_is_active
    ON telegram_partners (is_active);
CREATE INDEX IF NOT EXISTS ix_telegram_partners_sort_order
    ON telegram_partners (sort_order);

CREATE TABLE IF NOT EXISTS telegram_partner_photos (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    partner_id INTEGER NOT NULL REFERENCES telegram_partners(id) ON DELETE CASCADE,
    external_content_id INTEGER UNIQUE,
    image_url TEXT,
    file_path TEXT,
    sort_order INTEGER NOT NULL DEFAULT 0,
    is_cover INTEGER NOT NULL DEFAULT 0,
    created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP::TEXT,
    CHECK (image_url IS NOT NULL OR file_path IS NOT NULL)
);

CREATE INDEX IF NOT EXISTS ix_telegram_partner_photos_partner_id
    ON telegram_partner_photos (partner_id);
CREATE INDEX IF NOT EXISTS ix_telegram_partner_photos_sort_order
    ON telegram_partner_photos (sort_order);

CREATE TABLE IF NOT EXISTS telegram_partner_offers (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    partner_id INTEGER NOT NULL REFERENCES telegram_partners(id) ON DELETE CASCADE,
    external_content_id INTEGER UNIQUE,
    title TEXT NOT NULL,
    description TEXT,
    conditions TEXT,
    base_price REAL,
    member_price REAL,
    discount_percent REAL,
    is_active INTEGER NOT NULL DEFAULT 1,
    sort_order INTEGER NOT NULL DEFAULT 0,
    created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP::TEXT,
    updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP::TEXT
);

CREATE INDEX IF NOT EXISTS ix_telegram_partner_offers_partner_id
    ON telegram_partner_offers (partner_id);
CREATE INDEX IF NOT EXISTS ix_telegram_partner_offers_is_active
    ON telegram_partner_offers (is_active);
CREATE INDEX IF NOT EXISTS ix_telegram_partner_offers_sort_order
    ON telegram_partner_offers (sort_order);

CREATE TABLE IF NOT EXISTS telegram_privilege_codes (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    telegram_user_id TEXT,
    linked_client_id TEXT,
    web_client_id TEXT,
    linked_account_id TEXT,
    partner_id INTEGER NOT NULL REFERENCES telegram_partners(id) ON DELETE CASCADE,
    offer_id INTEGER REFERENCES telegram_partner_offers(id) ON DELETE SET NULL,
    code TEXT NOT NULL UNIQUE,
    status TEXT NOT NULL DEFAULT 'created',
    expires_at TEXT,
    used_at TEXT,
    created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP::TEXT,
    source_platform TEXT NOT NULL DEFAULT 'telegram',
    web_subscription_checked_at TEXT,
    access_snapshot TEXT,
    metadata TEXT
);

CREATE INDEX IF NOT EXISTS ix_telegram_privilege_codes_partner_id
    ON telegram_privilege_codes (partner_id);
CREATE INDEX IF NOT EXISTS ix_telegram_privilege_codes_offer_id
    ON telegram_privilege_codes (offer_id);
CREATE INDEX IF NOT EXISTS ix_telegram_privilege_codes_status
    ON telegram_privilege_codes (status);
CREATE INDEX IF NOT EXISTS ix_telegram_privilege_codes_expires_at
    ON telegram_privilege_codes (expires_at);
CREATE INDEX IF NOT EXISTS ix_telegram_privilege_codes_telegram_user_id
    ON telegram_privilege_codes (telegram_user_id);
CREATE INDEX IF NOT EXISTS ix_telegram_privilege_codes_linked_client_id
    ON telegram_privilege_codes (linked_client_id);
"""

POSTGRES_SCHEMES = {"postgres", "postgresql"}


class PostgresConnection:
    """Small adapter that keeps repository SQL using sqlite-style placeholders."""

    def __init__(self, database_url: str) -> None:
        if importlib.util.find_spec("psycopg2") is None:
            raise RuntimeError(
                "PostgreSQL TELEGRAM_APP_DATABASE_URL requires psycopg2-binary. "
                "Install it with: pip install -r requirements.txt"
            )

        import psycopg2
        from psycopg2.extras import RealDictCursor

        self._real_dict_cursor = RealDictCursor
        self._connection = psycopg2.connect(database_url)

    def __enter__(self) -> "PostgresConnection":
        return self

    def __exit__(self, exc_type: object, exc: object, traceback: object) -> None:
        if exc_type is None:
            self._connection.commit()
        else:
            self._connection.rollback()
        self.close()

    def execute(self, query: str, parameters: tuple[Any, ...] = ()) -> Any:
        cursor = self._connection.cursor(cursor_factory=self._real_dict_cursor)
        cursor.execute(query.replace("?", "%s"), parameters)
        return cursor

    def executescript(self, script: str) -> None:
        with self._connection.cursor() as cursor:
            cursor.execute(script)

    def commit(self) -> None:
        self._connection.commit()

    def close(self) -> None:
        self._connection.close()


def safe_database_url_summary(database_url: str) -> str:
    """Return a non-secret database target summary for logs and diagnostics."""
    parsed = urlparse(database_url)
    scheme = parsed.scheme or "<missing>"
    host = parsed.hostname or "local-file"
    port = parsed.port or "<default>"
    database = parsed.path.lstrip("/") or "<none>"
    return f"scheme={scheme} host={host} port={port} database={database}"


def database_scheme(database_url: str) -> str:
    return urlparse(database_url).scheme


def is_postgres_url(database_url: str) -> bool:
    return database_scheme(database_url) in POSTGRES_SCHEMES


def sqlite_path_from_url(database_url: str) -> str:
    parsed = urlparse(database_url)
    if parsed.scheme != "sqlite":
        raise ValueError(
            "TELEGRAM_APP_DATABASE_URL must start with sqlite://, postgresql://, or postgres://"
        )
    if parsed.netloc not in ("", "."):
        raise ValueError("SQLite database URL must use a local filesystem path")
    if database_url.startswith("sqlite:///"):
        return unquote(database_url.removeprefix("sqlite:///"))
    if database_url == "sqlite://":
        return ":memory:"
    raise ValueError("Use sqlite:///./telegram_app.db or sqlite:// for TELEGRAM_APP_DATABASE_URL")


def get_database_url() -> str:
    return get_settings().telegram_app_database_url


def get_database_path() -> str:
    return sqlite_path_from_url(get_database_url())


def connect(database_url: str | None = None) -> sqlite3.Connection | PostgresConnection:
    url = database_url or get_database_url()
    if is_postgres_url(url):
        return PostgresConnection(url)
    if database_scheme(url) != "sqlite":
        raise ValueError(
            "TELEGRAM_APP_DATABASE_URL must start with sqlite://, postgresql://, or postgres://"
        )
    path = sqlite_path_from_url(url)
    if path != ":memory:":
        Path(path).parent.mkdir(parents=True, exist_ok=True)
    connection = sqlite3.connect(path)
    connection.row_factory = sqlite3.Row
    connection.execute("PRAGMA foreign_keys = ON")
    return connection


def init_db(database_url: str | None = None) -> None:
    url = database_url or get_database_url()
    schema = POSTGRES_SCHEMA_SQL if is_postgres_url(url) else SQLITE_SCHEMA_SQL
    with connect(url) as connection:
        connection.executescript(schema)
